apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-123
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: 'nginx'
    repoURL: 'https://github.com/iyuroch/argocd-demo.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
