apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-123
  name: nginx-123
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-123
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx-123
    spec:
      containers:
      - image: nginx
        name: nginx
