apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-argocd
  name: test-argocd
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-argocd
  template:
      labels:
        app: test-argocd
    spec:
      containers:
      - image: nginx
        name: nginx
